# ----------------------------------------------
# Example macro file for the GammaRayTel
# Visualization with OpenGL 
# ----------------------------------------------
# Authors: R.Giannitrapani, F.Longo and G.Santin 
# ----------------------------------------------

#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
/control/saveHistory
/run/verbose 1
/tracking/storeTrajectory 2
/tracking/verbose 1
/gun/sourceGen true
#/control/execute emstd.mac

/run/initialize

/gun/particle proton
/gun/energy 20 GeV
/gun/vertexRadius 38.1 cm
/gun/sourceType 2 


# You can modify the geometry of the telescope via a messenger

#/payload/setNbOfTKRLayers 15
#/payload/update
#/payload/setTungstenDistance 5. mm 
#/payload/update

# Use this open statement to create an OpenGL view:
####/vis/open OGL 600x600-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
####/vis/viewer/set/autoRefresh false
####/vis/verbose errors
#
# Draw geometry:
####/vis/drawVolume
#
# Specify view angle:
####/vis/viewer/set/viewpointThetaPhi 90. 0.
#
# Specify zoom value:
#/vis/viewer/zoom 2.
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
####/vis/scene/add/trajectories smooth
####/vis/modeling/trajectories/create/drawByCharge
####/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
####/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
#
# Re-establish auto refreshing and verbosity:
####/vis/viewer/set/autoRefresh true
####/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush

# run 10 events
/run/beamOn 10


