# ----------------------------------------------
# Example macro file for the DmpSimu
# ----------------------------------------------
# Author(s): Xin Wu 
# ----------------------------------------------

#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
/control/saveHistory
/run/verbose 1
/tracking/storeTrajectory 2
#/tracking/verbose 1

/run/initialize

/gun/sourceGen true
/gun/particle proton
/gun/energy 20 GeV
/gun/vertexRadius 38.1 cm
/gun/sourceType 2 

# run 10 events
/run/beamOn 10


