import os
env = Environment(ENV = os.environ)

#set the programme name
ExeName='DmpSimu'

#set your G4 build folder
env.PrependENVPath('PATH', '/home/rui/work/geant4/build')

#set the G4 environments
env.Prepend(CPPFLAGS = '-DG4VIS_USE')
env.Append(CPPFLAGS = ' -DG4UI_USE')
env.Append(CPPFLAGS = ' -DG4VIS_USE_OPENGLX')

#set ROOT binary folder
env.PrependENVPath('PATH', '/home/rui/work/root/bin')

env.ParseConfig("geant4-config --cflags --libs")
env.ParseConfig("root-config --cflags --libs")
env.Prepend(CPPPATH=['global/include','STK/include','BGO/include','PSD/include'])

#sub_detector build
stk_obj=env.Object(Glob("STK/src/*.cc"))
bgo_obj=env.Object(Glob("BGO/src/*.cc"))
psd_obj=env.Object(Glob("PSD/src/*.cc"))
glb_obj=env.Object(Glob("global/src/*.cc"))

#main build
obj = stk_obj + bgo_obj + psd_obj + glb_obj + env.Object(Glob(ExeName+".cc"))  
env.Program('exe/'+ExeName,list(obj)) 

#clean up
#for item in list(obj):
#	Delete(item)

